# a=input('Enter your Name:')
# print("My Name is",int(a)) 
# print("My Name is",float(a)) 
# print("My Name is"+' '+str(a))
# print("My Name is"+' '+a)

# a=int(input('Enter your Phone Number:'))
# print("Your Phone Number is",a)
# print("Your Phone Number is",a,sep=" ")
# print("Your Phone Number is",int(a))
# print("Your Phone Number is",float(a))
# print("Your Phone Number is"+' '+str(a))

# a=float(input('Enter your BMI:'))
# print("Your BMI is",a)
# print("Your BMI is",a,sep=" ")
# print("Your BMI is",int(a))
# print("Your BMI is",float(a))
# print("Your BMI is"+' '+str(a))
